import { useUser } from '@/context/user'
import { authStateChanged } from '@/firebase/actions/auth'
import Section from '@/layout/Section'
import Head from 'next/head'
import { ReactElement, useEffect } from 'react'

export default function Document (): ReactElement {
  const { setUser } = useUser()

  useEffect(() => {
    authStateChanged(setUser)
  }, [])

  return (
    <>
      <Head>
        <title>Nuevo Documento</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Section>
        <h1>Creando</h1>
      </Section>
    </>
  )
}
