import { useUser } from '@/context/user'
import { authStateChanged } from '@/firebase/client'
import Head from 'next/head'
import { ReactElement, useEffect } from 'react'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export default function Home (): ReactElement {
  const { setUser } = useUser()

  useEffect(() => {
    authStateChanged(setUser)
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
    </>
  )
}
