import Header from '@/components/Header'
import LoginButton from '@/components/LoginButton'
import { loginWithGoogle } from '@/firebase/client'
import { User } from '@/types'
import Head from 'next/head'
import { ReactElement, useState } from 'react'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export default function Home (): ReactElement {
  const [user, setUser] = useState<User | null>(null)
  const handleLogin = (): void => {
    loginWithGoogle().then(res => {
      setUser(user)
      console.log(user)
    }).catch(console.error)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header>
        <div className='flex justify-between items-center h-full'>
          <p className='text-xl text-white'>Markdown docs</p>
          {
            user === null
              ? <LoginButton handleLogin={handleLogin} />
              : <p>{user.displayName}</p>
          }
        </div>
      </Header>
    </>
  )
}
