import useUser from '@/context/user'
import { authStateChanged } from '@/lib/firebase/actions/auth'
import { validateToken } from '@/lib/firebase/actions/authAdmin'
import Section from '@/layout/Section'
import Head from 'next/head'
import { useEffect } from 'react'
import { useRouter } from 'next/router'
import { GetServerSideProps, NextPage } from 'next'
import { getMarkdownDocByIdAndUser } from '@/lib/firebase/actions/documents'
import { MarkdownDocData } from '@/types'

export const getServerSideProps: GetServerSideProps = async (context) => {
  const { docId } = context.query
  const { email } = await validateToken(context)
  const documentData = await getMarkdownDocByIdAndUser(email as string, docId as string)

  return {
    props: {
      data: { ...documentData }
    }
  }
}

interface IProps {
  data: MarkdownDocData
}

const DocumentCompose: NextPage<IProps> = ({ data }) => {
  const { setUser } = useUser()
  const { query: { docId } } = useRouter()

  useEffect(() => {
    authStateChanged(setUser)
  }, [])

  return (
    <>
      <Head>
        <title>{data.title}</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Section>
        <pre>Creando {JSON.stringify(data, null, 2)}</pre>
      </Section>
    </>
  )
}

export default DocumentCompose
